DROP DATABASE if exists testims;
CREATE DATABASE IF NOT EXISTS `testims`;

DROP TABLE IF EXISTS `customers`;


CREATE TABLE IF NOT EXISTS `customers` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(40) DEFAULT NULL,
    `last_name` VARCHAR(40) DEFAULT NULL,
    `username` VARCHAR(40) DEFAULT NULL,
    `password` VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `items`;

CREATE TABLE IF NOT EXISTS `items` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`cost` DOUBLE DEFAULT NULL,
`name` VARCHAR(40) DEFAULT NULL,
PRIMARY KEY(`id`)
);

DROP TABLE IF EXISTS `orders`;

CREATE TABLE IF NOT EXISTS `orders` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`customerid` INT(11) DEFAULT NULL,
`cost` DOUBLE DEFAULT NULL,
PRIMARY KEY(`id`),
FOREIGN KEY(`customerID`) REFERENCES `customers`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);
